FROM ubuntu:20.04
MAINTAINER supperthomas <78900636@qq.com>
ARG DEST_DIR=/root

WORKDIR ${DEST_DIR}

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y git python3 python-is-python3 pip scons libncurses5-dev vim wget

RUN pip install requests -q

RUN wget -O- https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 | tar -xj 

RUN rm -rf rt-thread && git clone https://github.com/RT-Thread/rt-thread.git

WORKDIR /root/rt-thread

RUN python -c "import tools.menuconfig; tools.menuconfig.touch_env()"
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.env/tools/scripts:/root/gcc-arm-none-eabi-10.3-2021.10/bin:$PATH" \
    RTT_EXEC_PATH=/root/gcc-arm-none-eabi-10.3-2021.10/bin \
    RTT_CC=gcc
