FROM ubuntu:20.04
MAINTAINER supperthomas <78900636@qq.com>
ARG DEST_DIR=/root

WORKDIR ${DEST_DIR}

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y git python3 python-is-python3 pip scons libncurses5-dev vim wget

RUN pip install requests -q

RUN wget -O- https://github.com/RT-Thread/toolchains-ci/releases/download/v1.3/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 | tar -xj 

RUN mv gcc-arm-none-eabi-10-2020-q4-major gcc-arm-none-eabi

RUN rm -rf rt-thread && git clone https://github.com/RT-Thread/rt-thread.git --depth=1

WORKDIR /root/rt-thread

RUN python -c "import tools.menuconfig; tools.menuconfig.touch_env()"
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.env/tools/scripts:/root/gcc-arm-none-eabi/bin:$PATH" \
    RTT_EXEC_PATH=/root/gcc-arm-none-eabi/bin \
    RTT_CC=gcc
