FROM ubuntu:20.04
MAINTAINER supperthomas <78900636@qq.com>
ARG DEST_DIR=/root

WORKDIR ${DEST_DIR}

ADD . /work

RUN apt-get update

RUN apt-get upgrade -y

RUN apt-get install -y git

RUN apt-get install -y python3 python-is-python3 

RUN apt-get install -y pip

RUN apt-get install -y scons

RUN apt-get install -y libncurses5-dev

RUN apt-get install -y vim

RUN pip install requests -qq

#RUN python -c "import tools.menuconfig; tools.menuconfig.touch_env()"  这个是rtthread代码下载之后有的

RUN apt-get install -y wget

RUN wget -qO- https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 | tar -xj 

ENV PATH "/root/gcc-arm-none-eabi-10.3-2021.10/bin:$PATH"

ENV RTT_EXEC_PATH=/root/gcc-arm-none-eabi-10.3-2021.10/bin

#python -c "import tools.menuconfig; tools.menuconfig.touch_env()"


RUN apt-get clean

ENV RTT_CC=gcc


